project:
  type: book
  output-dir: docs

book:
  title: "nombre del curso"
  author: "nombre del autor"
  output-file: "nombre_del_repositorio"  
  date: today
  date-format: medium
  favicon: logo.png
  description: Descripcion del curso
  keyword: Palabras clave del curso
  url: https://github.com/userGithub/nombre_del_repositorio.git
  page-navigation: true
  sidebar: 
    logo: logo.jpg
    search: true
    collapse-level: 1

  repo-subdir: book
  sharing: [twitter, linkedin]
  downloads: [pdf, epub]
  image: logo.png

  page-footer:
    center: 
      - text: "About"
        href: about.qmd
      - text: "License"
        href: license.qmd
        
  chapters:
    - index.qmd
    - part: "Unidad 1: Nombre de la Unidad"
      chapters: 
        - unidades/unidad1/intro.qmd

bibliography: references.bib
biblio-style: "apalike"

format:
  html:
    number-sections: false
    theme: 
      dark:  solar #slate, darkly, solar, superhero, vapor
      # light: cosmo
    number-depth: 4
    link-external-icon: true
    link-external-newwindow: true
    css: css/styles.css

  pdf:
    documentclass: scrreprt
    classoption: ["onepage", "openany"]
    papersize: a4
    toc: true
    margin-top: 35mm
    margin-left: 30mm
    margin-bottom: 30mm
    margin-right: 30mm
    titlepage-geometry: 
      - top=35mm
      - bottom=30mm
      - right=30mm
      - left=30mm
  epub: 
    belongs-to-collection: "Nombre del Curso"
    group-position: 0
    creator: "Nombre del Autor"
    rights: "© Firma | año"
    fig-responsive: true
    number-sections: true